import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import DesktopNav from "@/components/DesktopNav";
import MobileNav from "@/components/MobileNav";

const jetBrains_Mono = JetBrains_Mono({
  subsets: ["latin"],
  weight: [
    "100", "200", "300", "400", "500", "600", "700", "800"
  ],
  variable: '--font-jetbrainsMono'
});

export const metadata: Metadata = {
  title: "TechDev",
  description: "Generated by ME!.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetBrains_Mono.variable}`}>
        <div className="hidden lg:block border-r border-r-white/20 h-[100vh] min-h-[100vh] min-w-[300px] max-w-[300px] fixed"> <DesktopNav /> </div>
        <div className="block lg:hidden border-b-white/20"> <MobileNav /> </div>
        <div className="lg:pl-[300px] w-full h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
